// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpcLB8965OHOMHhYrxUkUi6hdoyk8RFKo',
    appId: '1:459161114556:web:8c005c9145b451a1d4fdb9',
    messagingSenderId: '459161114556',
    projectId: 'instagram-clone-64fc1',
    authDomain: 'instagram-clone-64fc1.firebaseapp.com',
    storageBucket: 'instagram-clone-64fc1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjoKCkKnTClEhC6qlnnRzaMczAy7-_uTk',
    appId: '1:459161114556:android:2f10e8265a5cfec8d4fdb9',
    messagingSenderId: '459161114556',
    projectId: 'instagram-clone-64fc1',
    storageBucket: 'instagram-clone-64fc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDULbX6ielfG8c2q7lYPefju_l9cVnUi8c',
    appId: '1:459161114556:ios:ec88ec7221ae7271d4fdb9',
    messagingSenderId: '459161114556',
    projectId: 'instagram-clone-64fc1',
    storageBucket: 'instagram-clone-64fc1.appspot.com',
    iosClientId: '459161114556-bfh1kp8irsdf3i5chfffhdm2c3b5sdbq.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDULbX6ielfG8c2q7lYPefju_l9cVnUi8c',
    appId: '1:459161114556:ios:ec88ec7221ae7271d4fdb9',
    messagingSenderId: '459161114556',
    projectId: 'instagram-clone-64fc1',
    storageBucket: 'instagram-clone-64fc1.appspot.com',
    iosClientId: '459161114556-bfh1kp8irsdf3i5chfffhdm2c3b5sdbq.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );
}
